name: Docker Image CI

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image and publish to GitHub Packages
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
